---
apiVersion: v1
kind: ConfigMap
metadata:
  name: base-config
  namespace: flux-system
data:
  NFS_SERVER_ADDRESS: "nfs.voldemota.xyz"
  INTERNAL_ADDRESS: "home.voldemota.xyz"
  EXTERNAL_ADDRESS: "voldemota.xyz"
