apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich-ui-ingress
  namespace: photos
  # annotations:
  #   nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
    - host: immich.dev.voldemota.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: immich-server-svc
                port:
                  number: 2283
