apiVersion: ENC[AES256_GCM,data:xWE=,iv:5OPAGHCKfArnDRUAr7EaUm/pxwhjAJ8z6YmqDYiVVJ4=,tag:zqPBAv0Eq/cCToN2IbVeiw==,type:str]
kind: ENC[AES256_GCM,data:6WfYr2AT,iv:LVY0t9sTjX00YhI7XAcSjrIltCI18VYGiBmFBGpxPVQ=,tag:hU4uhMzRTtoQAGmPyMp8CA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wYlkrvcRBtf8YX+8B7/i,iv:EQsfeupcNOOTN3ieLuyRi9uTmiFB5xvM4dahXXvYMak=,tag:7Q32hh740LEmfa0cyEgupw==,type:str]
    namespace: ENC[AES256_GCM,data:HXXazPvX,iv:hZ60mFdV1b9I+nQvbpuuHXVDEWg/rE7OmRQGnmJ+FVg=,tag:ajEl/YD7jxzX0/2xhu5XrQ==,type:str]
type: ENC[AES256_GCM,data:SHAyqELG,iv:PAiZyNMoPVvGtmyzFvimRDrb8iJKg/ren1GOdAT6iVY=,tag:dJwM/XSM1yc7UMd2TFen2A==,type:str]
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:i+Q1jiVDUT6lkw==,iv:ye6wVAZf1e4KiFpv+tNKH7Dt3b7OyRBRoln00y7bW2k=,tag:Dhs13U29eshxBvut0IVtEw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:hROXMPtO,iv:jKqPOif2zrNvsYlWmZ830I41zoa5g7yVu7ZYx/p4H9A=,tag:POpGoB1NLAv7kQPrfaCAfQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:/InhgOS4,iv:6HOoA6SicF8vepYuq7LeR+bc6mQlIrFlclpf4Xh0OOY=,tag:PUJT1glV5L58QAELEM/h9g==,type:str]
sops:
    age:
        - recipient: age1zjduq5gd3mu24cqypn65lpj8f67075xsgeztsddarrgs8jyv5qtqs22guk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQkVsY1dlNVFkV1V2cEZS
            a0YxNkMrNitqUFdpKzcrYnhOL083aXU2V1RJCi9lQ2xIUG1rRzU5TXFjUE1raFFn
            bm9aMmtUbWFYRHBRN0plNzNJNi9tcVEKLS0tIEZkcHFseUdlYVdIWnJFUlJoZU10
            Z2J2Y3R0bHZjZFNWcWFKNXkwSm4zNHMKHhjlOEMh2t+csZf00v3KNtBGWVAuHwD3
            sQHbeat2pef1kmPX7cs646qFzNk52xF0uHnYOdGPjmKjxVYvFXho5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e2ww68t6ekwk3d6c6k7u6wswnutsuqtht75yseerf7nynsvj6ezq3wtwk7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cWkvY2RQeXM2UU1PMU1K
            anlTUGoweVZ2MmRkRDExNDN3Y1VCSVNRTEdzCjZ3bGFiNXArbnBnQlA2TWFWS1Nw
            Nk55UEpoMnM3WWEydEwwSzc3VE1UTFkKLS0tIFlYTTEyWFoyWkVjRmg3NHIwMDI4
            NkdIdTNpUEhYbUV2VEpRVXFTZlo2UlUK6Sc2rwHIteDf18FN4CidpJKOOUN0jw6i
            w13iFx9Y6T2dgjeX7aHl+/1zV2heiSDxQqt43ZPpsc2YNsJuhzCBMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-12T16:28:46Z"
    mac: ENC[AES256_GCM,data:CKvQeVIjHXaw3P/OjdzpkT5LGZjmb/oe6YcwvvbO+F13RlU/qg+KKXbX4BHKW5ig7vuchUvw19m2XJERc0TqwN7aNh23Z+3OXJvC+Rq3rOU+e/dE9Qq+RutRKsGRjLAGOs5wyN5qxf4VAUGhmSNXJA/jHBZrKZ4o/64xayVEoL8=,iv:XWvDb4EJ2SebsZXniQY/ZLjrY05hNASdQ0orB5UleCE=,tag:wFE7oQjhPwyDnHwh+/DYxQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
