apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-controller
  namespace: flux-system
spec:
  interval: 15m
  path: ./clusters/dev/platform/cert-manager/control
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
