---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/
  - apps-flux.yaml
  - cert-manager-cfg-kustomization.yaml
  - cert-manager-kustomization.yaml
  - metallb-crs-kustomization.yaml
  - metallb-kustomization.yaml
  - platform-flux.yaml
