---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfs-subdir-external-provisioner
  namespace: platform
spec:
  interval: 30m0s
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
