---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 00-base-config
  namespace: flux-system
spec:
  interval: 10m0s
  path: ../../infrastructure/overlays/prod/00-base-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
