---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 01-base-config
  namespace: flux-system
spec:
  interval: 2m30s
  path: ../../infrastructure/overlays/prod/01-base-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: 00-base
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: networking-metallb-speaker
      namespace: networking
    - apiVersion: apps/v1
      kind: Deployment
      name: platform-external-secrets
      namespace: platform
