---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 10-applications
  namespace: flux-system
spec:
  interval: 2m30s
  path: ../../apps/overlays/prod/10-applications
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: 04-services
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: base-map
