---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-base-config.yaml
  - 01-core.yaml
  - 02-core-config.yaml
  - 03-backends.yaml
  - 04-services.yaml
  - flux-system/
