---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps-base-reqs-flux.yaml
  - apps-flux.yaml
  - apps-reqs-flux.yaml
  - flux-system/
  - platform-config-flux.yaml
  - platform-controllers-flux.yaml
  - platform-prod-controllers-flux.yaml
  - pre-controllers-prod-flux.yaml
