---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-controller
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/prod/platform/networking/metallb/control
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
