---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-config
  namespace: flux-system
spec:
  interval: 10m
  path: ../../infrastructure/overlays/prod/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: platform-prod-controller
  postBuild:
    substitute:
      base-config:
        kind: ConfigMap
        name: base-config
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: speaker
      namespace: platform
    - apiVersion: apps/v1
      kind: Deployment
      name: longhorn-manager # Verify name
      namespace: longhorn-system
