---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-config
  namespace: flux-system
spec:
  interval: 10m
  path: ../../infrastructure/overlays/prod/config/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: platform-prod-controllers
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: base-config
        namespace: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: platform-metallb-speaker
      namespace: platform
    - apiVersion: apps/v1
      kind: DaemonSet
      name: longhorn-manager
      namespace: longhorn-system
