# infrastructure/overlays/prod/config/dragonfly/release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2 # Or v2beta1, check your Flux API version
kind: HelmRelease
metadata:
  name: dragonfly # Name for this release
  namespace: flux-system # Namespace where Dragonfly will run
spec:
  interval: 30m
  chart:
    spec:
      chart: .
      version: "1.34.2"
      sourceRef:
        kind: HelmRepository
        name: dragonflydb-oci
        namespace: flux-system
  install:
    createNamespace: true
  targetNamespace: dragonfly
  values:
    persistence:
      enabled: true
      storageClass: "longhorn"
      size: "10Gi"
    podSecurityContext:
      fsGroup: 2000
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
    snapshots:
      enabled: false
      # schedule: "* * * * *" # Example cron schedule
      # storage:
      #   s3:
      #     endpoint: "http://minio.minio.svc:9000" # Your MinIO service
      #     bucket: "dragonfly-backups"
      #     region: "us-east-1" # Or your region
      #     # You'll need a secret with AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
      #     credentialsSecret: "minio-creds"

    # Add any other prod-specific overrides here
    # replicas: 1
    # resources:
    #   requests:
    #     cpu: 100m
    #     memory: 256Mi
