---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secrets/
  - cert-manager/
  - dragonfly/
  - cloudnative-pg/
  - ingress-nginx/
  - repositories/
  - namespace.yaml
