apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/cloudnative-pg/
  - external-dns-internal/
  - dragonfly/
  - kube-prometheus-stack/
  - minio/
  - secret-stores/
