---
apiVersion: v1
kind: ConfigMap
metadata:
  name: base-map
  namespace: flux-system
data:
  EXTERNAL_ADDRESS: "voldemota.xyz"
  INTERNAL_ADDRESS: "home.voldemota.xyz"
  NFS_SERVER_ADDRESS: "nfs.svc.voldemota.xyz"
  SERVICES_ADDRESS: "svc.voldemota.xyz"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  svc-voldemota.server: |
    svc.voldemota.xyz:53 {
        errors
        cache 30
        forward . 192.168.1.4
    }
