---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/cert-manager/
  - ../../../base/external-secrets/
  - ../../../base/ingress-nginx/
  - ../../../base/metallb/
  - ../../../base/sealed-secrets/
  - config-maps.yaml
  - namespaces.yaml
  - rbac/
