---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../../base/media/immich/

patchesStrategicMerge:
  - patch.yaml

resources:
  - db.yaml
  - external-creds.yaml
  - immich-pvc.yaml
  - ns.yaml
