---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-api-token
  namespace: platform
spec:
  encryptedData:
    PI_HOLE_API_KEY: AgB/EkgrFEQVRAYsM7RXGcCQqqXvJfTzGCLiSnpE2S5jgz5KxkIqCW7V6gON38kRz+k/DBbKjry6iV+FFKxoTfQFgkrx1HrAn0Dbe7MX/coedP1afqCoDgepO5SA3mdDq2zmLKDHouxJNfdBsAE9bttCjcRsJDnBcHaQKEzEOQHaXg32OfE6pHmR/1b2kBgMqoPWYbjhbWtpkj67raLJ0zkuXdM4QTLP7lYjhOKK9drdCdANT0htKG6yqHhujbazIDrtC6TLo24fGt6hFFlqTlZXfOVHi6smOtcy7O+qqx7CJKbYgCDR54+NBPLqVCR3oV0ftE+njEloRZ66vHAgBDtapkbV073jN5Nl7cWYvF7qBoi72C4q5z2pNbm6H7QIc5TiNKqmgbWzyW2kjzevtecJ+UHNzLFvyttLatWC8F2BebFO949kYY2iK57Oc4Xn4Sn4vWgQ39fSGOEg0DAFWyRubbpecSwAPuw4SDBjpJ0Yu8mj/RXX47lUoqV8EHKJqTDKIlAf/96RTiSxYQjyyAUBsBsf9v9XLFozxjyG0UbEeQ/FG4E8ODKQ6bz5GRO9/a4IHy1PjALtaDxtFIWH21KjAjXFdW1JOjGegRgCDEnIzqXAs/YXUE0vxsrdT88pKhnXpsvnRUAlmdURvOO0OwGXpBP9QdB6TlAbte0sZKaTvSu19KYGAJUGP31Gn9CYR0Fm0FbZ58ETox88ge7kR5Dk8ehqt4bDzR7JinyEMn5UBq4KJvHZuNqbJScd7g==
  template:
    metadata:
      name: pihole-api-token
      namespace: platform
    type: Opaque
