---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: platform
spec:
  encryptedData:
    api-token: AgC+Ocu7FSHnzqtrbdnS0GVo999VJviyS+PixPfTgrXuw5rwJbbMTR0e8+pXLN7aNnR5nhOH3zW056EccR8fIxB7CtpGS/R59lhnZDmxLrsTy3Aw8vipXg93dvAcTI54Js+k0cdrBLPJEv/N7DTXf74v3P5cdF0ErXnCKVosZj5GJ6v8SdXLJB1izJnLtZtLDQAmxoaw8sQ3MSHiFjGdZsMGoDvIF4fPcy6CydRXB9otiFH+1kFglURQda+pU+boFs4lScuIKKbqitCXAzJ4B4ju75Edpj7+qnH1x9XLZGOCTh/3wzvCklXMkiuu9bda7/aFeeIucYnExSDqKDGSQ9a7+bg5ukJZ8uviBbQRz6eqXUhvSSnKc3yZv4E3d1eugTB5/5dJBiSRSWpqmM7vLPLwfFC6695X9/h1izgIsJ1nGlmcgjfWsv9wckcsyTqc9wPqH4kquMokRP0te0cxVrnBHl0mGbTWyvYRGDZV9NgYfs12QgdhG7FKiCZgczXkZ4tmSGyPexI1DJQgbCehw8IWO8oF/2wm+CSNGeP5QEJzMKxlcFfoGDlUzBxyzwAvyIjv5XkArTynguEU/r4O5sapb9gaaVe1i1Eu24F9HzMvCCsC2KhkD48gp4ovhbRljnhTvue8gqABQYbW+Hjiyt5rQCTd3kWjN6EJxCmVRBVu3gm8wqPR/pPeUqJASSSGZJKKeRqvUyBGGbsc4Z5966/SpplAyZpZFz2VDM7levyTlZ0ZxCpccy4l
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: platform
    type: Opaque
