---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: immich-db-secret
  namespace: photos
spec:
  encryptedData:
    DB_DATABASE_NAME: AgDFowcjmfPOCLkCyd1GA3iOQKs7mvScWUUbPWVSsgk0kIF0MyHraO8w4WtV74PTrdrhXZoLl3pow/BV7TeslXUZ/wcZ5T4NpmiJJJqAhvluEtN6/+6hOnrNU1NbSAJf/3tVKrBdbFEumdDB0jJPvGi/DrSgmr0GzTOXIhFz+GETusNgiI6IoldUGcpOW/H3lerj6dH1n0NEyE2ouvh4EWnh+6H5r/QHMBDsLPCHBldbTd03zP9hhOSlsf8k9ZoFdHiiLIX4k/ICht6C8yI6b6h1wbb8XckMyaSMHaZ46+wCT9EXAQMriNN4gd83VoLnr5UJT8S9fnPwyhfxHLwiLS6XSP/dFL0j8WYr2feKQh3X4av3C8j4voSAA5ftBMTF2zSXEt0PjBzFShRCRxWfkGGCfXZfAbCOfsn5lCLC2kDCCqx6WkWOLwa1zYHbsiKlo87zdWR8Aq+2HeJ/U6NO03iCaX4eSrKcfQ3xBYornIJ7txaZN9Epw3lYB1N2idbC98XAqDxOlHsfP/beNou/NxxPKToNuXII6twc+NLwvMRgFqjeGzIGlNVJwlhDPqMlS6qubLeaoMYWs/AJBDRSB9CJa0autPRwzqLrMWEkzwN5cTMaZK8pfjmw+rMSAAsXrJSznxWEgesHE7tTM9K+CJjlbDF4QZjUH8Ueaqc062zs+XoGSqV9EYuLmdOyI+Uzhg0xMwinw2w=
    DB_PASSWORD: AgAz/gAiL1Qxf59dUDq/5avVY+pOgR1MOK+6MgOONE57z/hhk8t/TVu7KqDeD2oKnCCyET2RCU9bxoPZ/7GCR4ddHSQED860GPi56g3RtB4GgpdNcg9Bv+sREryYGQAdw8w31nFdSC6CAj1vAAdN9DUqHrzum9s7PwAvMRqPZkbBzgegO+NJusnTjC23oGhvrrryvNn7fvh7EvTvohWRrcDqLjaaYuQlWxK7fsPCgCk/f2CjmdPRAjT5BQtSGk3kSuT3VPYj0xF1HIpKZojcIlFISjCRzNExc+EKAaZsduHpAsjAkUmGDuMqtF6W/oJPFislnaxMx2gn+mNdAEgGKgjG+XIlRCEbNq492bgdg7rauEiFFzWa7WdPQXC2H0ZXU2lwwpRoFUsTd9IU/Ii8PM6OIKmxQQjSuR4IEp6dLfxRMLUGL4wQYlKE0bzYHgY++muydtX68qpE2FLGLGKXGleoTE3IG3c7QDWLIVXaukHRUm9kvnqGr3SQGFKQjwBeWN3FtH70UWwdymFX2iONaYIBcy14dWkMEJW+Z/ZMqp0ZjXdw2HxgoHSCSNJCzgFVXakeGwqER1s4x8Xq0ySsB6ZWWZJIhPNzDVCzvGVVUG4emgX868J6BgNWMJYqsK5amBgKTvmC0tV2jybKAc0vfAdH34FSD0QmZ4/NymsGY+HNR2zHx54W7usCuxWdFgIQ3m73oai4tdEsumjc
    DB_USERNAME: AgAxlu+iulxIWECJNTpAnvPqX84XyK/UM3BWfQz1E7Y+dCkvmbPSKzzKDEmWRhJiwP6kBY0lx649ArFLexMvMw3fGbhQxHbm9nkbvL+lgspbpfsB+fzXuKJAOOB2fn5YDo9HvT5CYVzqa/j0T5fs/QIQ1zrwkE8g6r019vzCRF6smu9QjsYTypyYpcwN1E1lp/6MjoD8J8Ta6aqDgSRn2BI0icSPebryt7xo/2jrn+Oxd289sXt+xMxbkL+CYkophFIob9nNRuqVPUXO+lfY4PCgtwB6hn9vPUU+c2uVTMb4dx1FkKZwWnNVEpLPpZpI8Jklu61+OPAnu7du6x3D7MoWg7rDidI2FFLgammglz6S3kMbPQ9p3mavJeHpb3UpxAXzFKkqCSqNnXBMVC//ynpTE4k/DOglzYP+N0lirYMhw8GeafWfx1cDDHqj7pScnZHK1MYLXOp58VY4b9OKnwEqpqI333AkJiK88JzslB0CB5AVUfyY7LBRluqebr7dQLF9vH7mETWNsuokCOa2O65OnqfuCI4gFiGqsXepoFYWeJCqhO/Ft7leGG1f4rS0EwTrScB/iwacJCpz/zV1+KAXZBIPbcoKeDZ/4oczPe8+RO+/JlLpd27QRakJO7xmpGJGVFQdX72SLUELLfjvd0GpgOND63otvLg+z3aRWkdRrWhQfX4C8InKeEWZ1MdQn2EfStVXlgYheQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: immich-db-secret
      namespace: photos
    type: Opaque
