---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: pi-hole-token
  namespace: platform
spec:
  encryptedData:
    PI_HOLE_ADMIN_TOKEN: AgBH1Nb/J/aVC/+iMI9uaH3CEiQJ01s82fnG5TSTyKoMTVJjN1+NyBAg2m/oi6Xpa/vkySUFDhVEy3jxH5sAAd7vcEpV3Je4OGJSTfzZsdlDZjgDvX7CmwnxikBQCteHY/otMA6Vjc6FNkkmx0FnL0vgFAMHQoEWnfZjLowUU4wluae7V7ARkfvL0ubmfjZN+UuuGG76zMezrN9vih75VXDPxskjDQLQrtzQMW+anmhPD4L3KnO7BFpNoj1KiGYFtuyhFhMjPNoVAln7/oxrpxfyx1Jfdh6WbS5Hs6lIBwFV8bBOLEdnoQ1zTSWpJYRzV2qr6m2c3RWclHoY+9P6+AZlFmGf+eRDyXE854VTk6Ngm48rBLxjzJ+Ygqb4IwFq46DIew46K8IhQ4Xrfiwaq2ePZfX2EGdnhz9s5N+vF73rSdley9iq4PGb9ms3jM9DSQTr6jbKmy65ESUz2x3Pxz5u47kl207WWACmqo+nsbVX4/soFGZWh+pPJJEbrV6pj2AIcbks0RnCaWTKF8DBD+QNUs02g9yg1cINT67EsfUe1vMRp1CjcwzCgM3GXRCDwzF0ksJmNiH7O2Jk/WcJSHhMDwBIzSEosHncHtVcnRb0XlusLA1Mi2Quz2oO5cypLBAY7qfXXGPPHalrWsuT6t0oH7JFVhhsaQsKDEyaaMmXCtFMWksGIVOvXkt683l/EtbiaJ/dwO8pWNofbmcxhZsDt/zwgBmRvaUwnazx/aIlbg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: pi-hole-token
      namespace: platform
    type: Opaque
