---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: pi-hole-secrets
  namespace: platform
spec:
  encryptedData:
    PI_HOLE_ADMIN_TOKEN: AgCSBgZ9InI9BjpReFf9QKn+aJ27v+O+YSlotlfUjfmO0S5XLezTTeMh0gZJtBHN8jeHOwLGI0BSWOvj+o1r5cHY14HWRZz5WL5DjagTZqOvjL+yh7Rgej2RmCrWUjeZLGpIitLXiopCxmk5ZlJGzbTbLB8ZjUU8BKdBRpRVq6UkuezhPO/u3rZe1nvpFuXeaw4vFY9uIrOrr6GM8sACaxg1kcQrQMwJbyqRy6DlTH+iatswQ3JXt4kSTtquYoGURJQSgm89ks0zgfKD8CBTnyGUuAhgCPXjECoHu8Y5+/l14Pf9WR5IiY/T4QicuLLVQiPCPhW8SiQpJb583ZdIhsD0iRNhG451iZOnZo79DlkYlM2ADJH0Pwdm1Pag0Nvq7/ZvuSEI6+7gMb2PhsT+mlyraopUR/97KkZiLC1xot5gcfnm45EgZTlSJCCOydEc2WCADJCLfcHUyLkzzISAEWLD4XpMdacFBk3T13LvQScOfc/BDz4WdQQIw5wmR0l7dHABZi/rpIrcrrS2ftQnYSn0VA/mxARDYPVqwGATD9wEURFyW8ZB65s+GAclYCgF8LzqyZFXw8qq2k4Rx9elgPPopwVnL3Wk2qFI/eOHH/AvTkoL99Y6VGytIEE778BaSH0KOT+aWJY/DYB7OB78M0wH8/+6Zp90Hwx/vRuUp4IAOdzfrLeCbwv29JLmqkW6Jn+2l4d8+1HTfb5DEQCQA3fVw854f8HKD+sxKylzC6CkDg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: pi-hole-secrets
      namespace: platform
    type: Opaque
