---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../../base/infisical/

patchesStrategicMerge:
  - patch.yaml

resources:
  - infisical-sealed.yaml
  - infisical-psql-creds-sealed.yaml
  - external-secret.yaml
  - psql-ifisical.yaml
